### ISSUE TITLE
Bugs (and fixes)

### ISSUE THREAD

**Issue by mlomb** [avinal/blowfish#2]
Hello, I tried to use your library but couldn't get it to work.
I'm migrating some Rust code to C++ (yeah, sad), so I had [a reference](https://docs.rs/rust-crypto/latest/src/crypto/blowfish.rs.html) to compare.

I found a coulple of bugs:

------

https://github.com/avinal/blowfish/blob/b6931e3196a4c5dd6e28cba7530791dc0a490105/src/blowfish.cc#L238-L238

Since `key` is a string, `key[j]` returns a signed char, which breaks my keys that are arrays of unsigned chars. So I changed:

```c++
data = (data << 8) | (unsigned char)key[j];
```

imho the key should not be a string

------

https://github.com/avinal/blowfish/blob/b6931e3196a4c5dd6e28cba7530791dc0a490105/src/blowfish.cc#L254-L260

The array should be indexed by `k` instead of `j`.

------

`Sboxes` in being indexed incorrectly in `F`:

https://github.com/avinal/blowfish/blob/b6931e3196a4c5dd6e28cba7530791dc0a490105/src/blowfish.cc#L269-L277

I changed it to (like the reference):

```c++
a = x >> 24;
b = (x >> 16) & 0xFF;
c = (x >> 8) & 0xFF;
d = x & 0xFF;
```

-----

After those changes, I get the same results as in Rust!
Hope this helps someone who comes across this library

**Comment by avinal** [comment]
Hey @mlomb, thank you so much for taking time to go through the code. I will follow up and fix them in coming weekend. 

I created this for a software engineering assignment. So bugs are expected.

**Comment by avinal** [comment]
The second mistake is a great example of how robust the Blowfish algorithm is. Because of the symmetry, it worked even though it was wrong. I have fixed them now. Thank you again
